# IoT Project - Cloud infrastructure
# Services:
#   - InfluxDB
#   - Grafana
#   - EMQX MQTT Broker
#   - Telegraf
#
# ---------------------------------------------------------------------------- #
version: '3'
services:
  # -------------------------------------------------------------------------- #
  # InfluxDB
  # Main Database for the project
  influxdb:
    container_name: iot-influxdb
    restart: unless-stopped
    image: influxdb:2.7
    volumes:
      - ./influx/data:/var/lib/influxdb2:rw
    ports:
      - 8086:8086
    healthcheck:
      test: "curl -f http://localhost:8086/ping"
      interval: 5s
      timeout: 10s
      retries: 5
  # -------------------------------------------------------------------------- #
  # Grafana
  # Dashboard for the project
  grafana:
    image: grafana/grafana:10.0.1
    container_name: iot-grafana
    restart: unless-stopped
    user: 1000:1000
    volumes:
      - ./grafana/data:/var/lib/grafana
      - ./grafana/grafana.ini:/etc/grafana/grafana.ini
    ports:
      - 3000:3000
    healthcheck:
      test: "curl -f http://localhost:3000/api/health"
      interval: 5s
      timeout: 10s
      retries: 5
  # -------------------------------------------------------------------------- #
  # Telegraf
  # Data collector for the project
  telegraf:
    image: telegraf:1.27.1
    container_name: iot-telegraf
    restart: unless-stopped
    volumes:
      - ./telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:ro
  # -------------------------------------------------------------------------- #
  # EMQX MQTT Broker
  # MQTT Broker for the project
  emqx:
    image: emqx/emqx:5.1.1
    container_name: iot-emqx
    restart: unless-stopped
    ports:
      - 1883:1883
      - 8083:8083
      - 8084:8084
      - 8883:8883
      - 18083:18083
    volumes:
      - ./emqx/data:/opt/emqx/data
      - ./emqx/log:/opt/emqx/log
      - ./emqx/etc/emqx.conf:/opt/emqx/etc/emqx.com


    healthcheck:
      test: ["CMD", "/opt/emqx/bin/emqx_ctl", "status"]
      interval: 5s
      timeout: 25s
      retries: 5
  # -------------------------------------------------------------------------- #
  # Cloudflare Tunnel
  tunnel:
    container_name: iot-tunnel
    image: cloudflare/cloudflared
    restart: unless-stopped
    command: tunnel run
    environment:
      - TUNNEL_TOKEN=eyJhIjoiMTFlZDA3Njk4ZmIzNGMzMDk1MjhhNWI2ZGZhMWI5ZmUiLCJ0IjoiNTZiMmJiMWUtZDgwOC00YmVkLTgzMjctNmIxYmMzOTRjNmIzIiwicyI6IlpqbG1Nak0wWkRjdFpUYzBNeTAwTmpNMkxXRmpZalF0WW1GbU9USmtNV0ZtWlRobSJ9
# ---------------------------------------------------------------------------- #
# Main Network
networks:
  default:
   name: IoTNetwork
   # external: true
# ---------------------------------------------------------------------------- #
